language: c

compiler:
 - gcc
 - clang

before_install:
- sudo apt-get install -qq python-docutils

before_script:
- apt-get source -q varnish
- cd varnish*
- ./configure --prefix=/usr/local
- make install
- cd ..
- ./autogen.sh
- ./configure --prefix=/usr/local VARNISHSRC=varnish* VMODDIR=/usr/local/lib/varnish/vmods
- make

branches:
  only:
    - master
    - develop

script:
- make check

